print("Hello I am a Console Chatbot!!")
print("What's your name?")
name=input()
print("Hello " + name)
print("How are you doing today? Say good or not good")
feeling=input()
print("Ok you are feeling, " + feeling)
print(Say Bye)
bye=input()
print(bye)

